# Change baseurl before deploy
baseurl      = "https://juheon.com/"
languageCode = "ko-kr"
title        = "JU HEON's BLOG"

# Theme i18n support
# See all available values at https://github.com/CaiJimmy/hugo-theme-stack/tree/master/i18n
defaultContentLanguage = "ko"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = true

# Change it to your Disqus shortname before using
disqusShortname = "ju-heons-blog"

[pagination]
    pagerSize = 5

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"